// Mocks generated by Mockito 5.0.8 from annotations
// in flutter_starter/test/nullsafety_unit_testing.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'nullsafety_unit_testing.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Cat].
///
/// See the documentation for Mockito's code generation for more information.
class MockCat extends _i1.Mock implements _i2.Cat {
  MockCat() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> chew(String? txt) =>
      (super.noSuchMethod(Invocation.method(#chew, [txt]),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
}
